#!/bin/sh

. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

if ! command_exists python ; then
  echo "Python 2.7 or 3 is needed to run this git hook"
  echo "Either:"
  echo "  1. Install Python 2.7/3, or"
  echo "  2. Run 'yarn format', then commit with '--no-verify'"
  echo ""
  exit 1
fi

cd js
yarn format:staged-only
